# Convex hull as diagnostic tool in single-molecule localization microscopy
# Lookup tables convex hull measures
Generation of lookup tables 1-4 providing threshold values to filter clustered SMLM data.

In [1]:
import numpy as np
import pandas as pd

import src.convex_hull as ch

The errors of the values displayed in the tables are not shown since they are smaller than 0.01. This is shown by calculating the standard error of means (SEM) with the highest standard deviation value of the particular table.

## Perimeter

In [2]:
measure = "peri_2d"
seed = np.random.default_rng(100)
n_max_points = 200
n_simulations_pt_1 = 1000
n_simulations_pt_2 = 100
sigma = 1
quantile_1 = 0.995
quantile_2 = 0.005
save_to = r"lookup_tables\lookup_table_peri_2d.csv"

lookup_table_peri = ch.lookuptable_ray(measure, seed, n_max_points, n_simulations_pt_1, n_simulations_pt_2, sigma, 
                                       quantile_1, quantile_2, save_to)

(perimeter_ray pid=5679)
(perimeter_ray pid=5675)
(perimeter_ray pid=5672)
(perimeter_ray pid=5677)
(perimeter_ray pid=5676)
(perimeter_ray pid=5673)
(perimeter_ray pid=5675)
(perimeter_ray pid=5675)
(perimeter_ray pid=5674)
(perimeter_ray pid=5677)

In [3]:
representation = lookup_table_peri.iloc[:, np.r_[0:10, 197]]
representation.insert(loc=10, column="...", value="...")
representation

$n$,3,4,5,6,7,8,9,10,11,12,...,200
$E(P_{ch}(n))$,5.32,6.47,7.31,7.96,8.50,8.94,9.33,9.67,9.97,10.24,...,17.25
$Mean(P_{ch}(n))$,5.33,6.47,7.31,7.97,8.50,8.94,9.33,9.68,9.97,10.23,...,17.26
$std_{pos}(n)$,2.11,2.06,1.99,1.95,1.90,1.86,1.83,1.81,1.77,1.74,...,1.16
$std_{neg}(n)$,1.77,1.79,1.78,1.74,1.71,1.68,1.65,1.63,1.61,1.59,...,1.02
$quant_{0.995}(n)$,11.04,11.96,12.62,13.16,13.49,13.92,14.21,14.50,14.67,14.90,...,20.43
$quant_{0.005}(n)$,1.29,2.24,3.06,3.79,4.34,4.79,5.27,5.70,6.01,6.34,...,14.76

In [4]:
std_pos = lookup_table_peri.loc["$std_{pos}(n)$"].astype(float).values
std_neg = lookup_table_peri.loc["$std_{neg}(n)$"].astype(float).values
stds = np.concatenate((std_pos, std_neg))
highest_value = np.max(stds)
sem = highest_value / np.sqrt(n_simulations_pt_1 * n_simulations_pt_2)
print("The highest standard error of means is " + "{:.4f}".format(sem))

The highest standard error of means is 0.0067

## Area

In [5]:
measure = "area_2d"
seed = np.random.default_rng(100)
n_max_points = 200
n_simulations_pt_1 = 1000
n_simulations_pt_2 = 100
sigma = 1
quantile_1 = 0.995
quantile_2 = 0.005
save_to = r"lookup_tables\lookup_table_area_2d.csv"

lookup_table_area = ch.lookuptable_ray(measure, seed, n_max_points, n_simulations_pt_1, n_simulations_pt_2, sigma, 
                                       quantile_1, quantile_2, save_to)

(area_ray pid=5679)
(area_ray pid=5676)
(area_ray pid=5673)
(area_ray pid=5675)
(area_ray pid=5673)
(area_ray pid=5676)
(area_ray pid=5673)
(area_ray pid=5675)
(area_ray pid=5675)
(area_ray pid=5672)
(area_ray pid=5673)

In [6]:
representation = lookup_table_area.iloc[:, np.r_[0:10, 197]]
representation.insert(loc=10, column="...", value="...")
representation

$n$,3,4,5,6,7,8,9,10,11,12,...,200
$E(A_{ch}(n))$,0.87,1.73,2.51,3.21,3.83,4.40,4.91,5.38,5.81,6.21,...,21.05
$Mean(A_{ch}(n))$,0.87,1.73,2.51,3.21,3.83,4.39,4.91,5.38,5.82,6.21,...,21.06
$std_{pos}(n)$,1.23,1.59,1.82,1.98,2.07,2.16,2.23,2.30,2.32,2.35,...,2.60
$std_{neg}(n)$,0.56,0.91,1.14,1.31,1.43,1.53,1.61,1.68,1.74,1.78,...,2.20
$quant_{0.995}(n)$,4.58,6.50,7.88,8.94,9.81,10.59,11.30,11.88,12.33,12.91,...,28.30
$quant_{0.005}(n)$,0.00,0.09,0.28,0.54,0.81,1.10,1.40,1.70,1.96,2.26,...,15.74

In [7]:
std_pos = lookup_table_area.loc["$std_{pos}(n)$"].astype(float).values
std_neg = lookup_table_area.loc["$std_{neg}(n)$"].astype(float).values
stds = np.concatenate((std_pos, std_neg))
highest_value = np.max(stds)
sem = highest_value / np.sqrt(n_simulations_pt_1 * n_simulations_pt_2)
print("The highest standard error of means is " + "{:.4f}".format(sem))

The highest standard error of means is 0.0083

## Surface area

In [8]:
measure = "area_3d"
seed = np.random.default_rng(100)
n_max_points = 200
n_simulations_pt_1 = 10000
n_simulations_pt_2 = 100
sigma = 1
quantile_1 = 0.995
quantile_2 = 0.005
save_to = r"lookup_tables\lookup_table_area_3d.csv"

lookup_table_surf_area = ch.lookuptable_ray(measure, seed, n_max_points, n_simulations_pt_1, n_simulations_pt_2, 
                                            sigma, quantile_1, quantile_2, save_to)

(surface_area_ray pid=5677)
(surface_area_ray pid=5678)
(surface_area_ray pid=5679)
(surface_area_ray pid=5677)
(surface_area_ray pid=5676)
(surface_area_ray pid=5676)
(surface_area_ray pid=5676)
(surface_area_ray pid=5678)
(surface_area_ray pid=5672)
(surface_area_ray pid=5672)
(surface_area_ray pid=5673)
(surface_area_ray pid=5675)
(surface_area_ray pid=5678)
(surface_area_ray pid=5678)
(surface_area_ray pid=5673)
(surface_area_ray pid=5675)
(surface_area_ray pid=5676)
(surface_area_ray pid=5676)
(surface_area_ray pid=5678)
(surface_area_ray pid=5678)
(surface_area_ray pid=5673)
(surface_area_ray pid=5673)
(surface_area_ray pid=5676)
(surface_area_ray pid=5676)
(surface_area_ray pid=5672)
(surface_area_ray pid=5673)
(surface_area_ray pid=5676)
(surface_area_ray pid=5679)
(surface_area_ray pid=5676)
(surface_area_ray pid=5673)
(surface_area_ray pid=5676)
(surface_area_ray pid=5677)
(surface_area_ray pid=5672)
(surface_area_ray pid=5672)
(surface_area_ray pid=5678)
(surface_area_ray pid=5674)
(surface_area_ray pid=5673)
(surface_area_ray pid=5673)
(surface_area_ray pid=5673)
(surface_area_ray pid=5674)
(surface_area_ray pid=5673)
(surface_area_ray pid=5675)
(surface_area_ray pid=5675)
(surface_area_ray pid=5673)
(surface_area_ray pid=5676)
(surface_area_ray pid=5679)
(surface_area_ray pid=5673)
(surface_area_ray pid=5674)
(surface_area_ray pid=5678)
(surface_area_ray pid=5673)
(surface_area_ray pid=5673)
(surface_area_ray pid=5678)
(surface_area_ray pid=5678)
(surface_area_ray pid=5676)
(surface_area_ray pid=5677)
(surface_area_ray pid=5678)
(surface_area_ray pid=5675)
(surface_area_ray pid=5679)
(surface_area_ray pid=5678)
(surface_area_ray pid=5672)
(surface_area_ray pid=5677)
(surface_area_ray pid=5677)
(surface_area_ray pid=5672)
(surface_area_ray pid=5674)
(surface_area_ray pid=5674)
(surface_area_ray pid=5678)
(surface_area_ray pid=5674)
(surface_area_ray pid=5673)
(surface_area_ray pid=5677)
(surface_area_ray pid=5676)
(surface_area_ray pid=5679)
(surface_area_ray pid=5675)
(surface_area_ray pid=5674)
(surface_area_ray pid=5673)
(surface_area_ray pid=5676)
(surface_area_ray pid=5677)
(surface_area_ray pid=5677)
(surface_area_ray pid=5675)
(surface_area_ray pid=5673)
(surface_area_ray pid=5679)
(surface_area_ray pid=5677)
(surface_area_ray pid=5679)
(surface_area_ray pid=5676)
(surface_area_ray pid=5676)
(surface_area_ray pid=5677)
(surface_area_ray pid=5675)
(surface_area_ray pid=5672)
(surface_area_ray pid=5675)
(surface_area_ray pid=5678)
(surface_area_ray pid=5674)
(surface_area_ray pid=5673)
(surface_area_ray pid=5679)
(surface_area_ray pid=5673)
(surface_area_ray pid=5678)
(surface_area_ray pid=5675)
(surface_area_ray pid=5679)
(surface_area_ray pid=5677)
(surface_area_ray pid=5675)
(surface_area_ray pid=5674)
(surface_area_ray pid=5676)
(surface_area_ray pid=6293)
(surface_area_ray pid=5674)
(surface_area_ray pid=5678)

In [9]:
representation = lookup_table_surf_area.iloc[:, np.r_[0:10, 196]]
representation.insert(loc=10, column="...", value="...")
representation

$n$,4,5,6,7,8,9,10,11,12,13,...,200
$E(SA_{ch}(n))$,6.93,10.05,12.84,15.33,17.59,19.64,21.51,23.25,24.86,26.36,...,84.21
$Mean(SA_{ch}(n))$,6.92,10.06,12.83,15.33,17.59,19.62,21.52,23.25,24.87,26.35,...,84.21
$std_{pos}(n)$,4.51,5.35,5.87,6.26,6.54,6.74,6.93,7.04,7.17,7.26,...,7.57
$std_{neg}(n)$,2.92,3.69,4.24,4.66,4.99,5.23,5.45,5.63,5.77,5.88,...,6.70
$quant_{0.995}(n)$,20.12,25.53,29.62,33.13,36.10,38.58,40.94,42.91,44.77,46.54,...,104.69
$quant_{0.005}(n)$,1.04,2.25,3.59,5.00,6.37,7.75,9.06,10.29,11.50,12.66,...,67.77

In [10]:
std_pos = lookup_table_surf_area.loc["$std_{pos}(n)$"].astype(float).values
std_neg = lookup_table_surf_area.loc["$std_{neg}(n)$"].astype(float).values
stds = np.concatenate((std_pos, std_neg))
highest_value = np.max(stds)
sem = highest_value / np.sqrt(n_simulations_pt_1 * n_simulations_pt_2)
print("The highest standard error of means is " + "{:.4f}".format(sem))

The highest standard error of means is 0.0078

## Volume

In [11]:
measure = "vol_3d"
seed = np.random.default_rng(100)
n_max_points = 200
n_simulations_pt_1 = 10000
n_simulations_pt_2 = 100
sigma = 1
quantile_1 = 0.995
quantile_2 = 0.005
save_to = r"lookup_tables\lookup_table_vol_3d.csv"

lookup_table_vol = ch.lookuptable_ray(measure, seed, n_max_points, n_simulations_pt_1, n_simulations_pt_2, sigma, 
                                      quantile_1, quantile_2, save_to)

(volume_ray pid=6294)
(volume_ray pid=5678)
(volume_ray pid=5674)
(volume_ray pid=5675)
(volume_ray pid=5674)
(volume_ray pid=5676)
(volume_ray pid=5676)
(volume_ray pid=5674)
(volume_ray pid=5674)
(volume_ray pid=6293)
(volume_ray pid=5673)
(volume_ray pid=6293)
(volume_ray pid=5679)
(volume_ray pid=5675)
(volume_ray pid=5675)
(volume_ray pid=5676)
(volume_ray pid=5675)
(volume_ray pid=5676)
(volume_ray pid=5678)
(volume_ray pid=5673)
(volume_ray pid=5676)
(volume_ray pid=5675)
(volume_ray pid=5674)
(volume_ray pid=5674)
(volume_ray pid=6293)
(volume_ray pid=6293)
(volume_ray pid=6293)
(volume_ray pid=5673)
(volume_ray pid=5674)
(volume_ray pid=5678)
(volume_ray pid=5679)
(volume_ray pid=5673)
(volume_ray pid=5675)
(volume_ray pid=5679)
(volume_ray pid=5673)
(volume_ray pid=5674)
(volume_ray pid=5676)
(volume_ray pid=6293)
(volume_ray pid=5674)
(volume_ray pid=6294)
(volume_ray pid=5679)
(volume_ray pid=6294)
(volume_ray pid=5674)
(volume_ray pid=5675)
(volume_ray pid=5674)
(volume_ray pid=5678)
(volume_ray pid=6294)
(volume_ray pid=6293)
(volume_ray pid=5675)
(volume_ray pid=5678)
(volume_ray pid=5679)
(volume_ray pid=5675)
(volume_ray pid=5679)
(volume_ray pid=5674)
(volume_ray pid=5676)
(volume_ray pid=5678)
(volume_ray pid=6293)
(volume_ray pid=6294)
(volume_ray pid=5678)
(volume_ray pid=6294)
(volume_ray pid=6559)
(volume_ray pid=6294)
(volume_ray pid=5673)
(volume_ray pid=6558)
(volume_ray pid=5675)
(volume_ray pid=6294)
(volume_ray pid=5675)
(volume_ray pid=5676)
(volume_ray pid=5673)
(volume_ray pid=6558)
(volume_ray pid=6558)
(volume_ray pid=5673)
(volume_ray pid=6294)
(volume_ray pid=5673)
(volume_ray pid=5673)
(volume_ray pid=5673)
(volume_ray pid=6558)
(volume_ray pid=5676)
(volume_ray pid=6293)
(volume_ray pid=6558)
(volume_ray pid=6558)
(volume_ray pid=6293)
(volume_ray pid=5675)
(volume_ray pid=5675)
(volume_ray pid=6558)
(volume_ray pid=6558)
(volume_ray pid=6294)
(volume_ray pid=5678)
(volume_ray pid=6559)
(volume_ray pid=5678)
(volume_ray pid=5673)
(volume_ray pid=5676)
(vo pid=5673) lume_ray
(volume_ray pid=5673)
(volume_ray pid=6294)
(volume_ray pid=6559)
(volume_ray pid=5676)
(volume_ray pid=6558)
(volume_ray pid=6293)
(volume_ray pid=5676)
(volume_ray pid=5675)
(volume_ray pid=5676)
(volume_ray pid=5673)
(volume_ray pid=5676)
(volume_ray pid=6734)
(volume_ray pid=6559)
(volume_ray pid=6734)
(volume_ray pid=5676)
(volume_ray pid=6558)
(volume_ray pid=5673)
(volume_ray pid=6734)
(volume_ray pid=5676)
(volume_ray pid=5676)
(volume_ray pid=6734)
(volume_ray pid=5673)
(volume_ray pid=6734)
(volume_ray pid=6559)
(volume_ray pid=6734)
(volume_ray pid=6558)
(volume_ray pid=6558)
(volume_ray pid=6807)

In [12]:
representation = lookup_table_vol.iloc[:, np.r_[0:10, 196]]
representation.insert(loc=10, column="...", value="...")
representation

$n$,4,5,6,7,8,9,10,11,12,13,...,200
$E(V_{ch}(n))$,0.53,1.33,2.25,3.22,4.21,5.19,6.15,7.10,8.02,8.91,...,63.72
$Mean(V_{ch}(n))$,0.53,1.33,2.25,3.22,4.21,5.18,6.16,7.10,8.02,8.91,...,63.71
$std_{pos}(n)$,0.94,1.55,2.07,2.52,2.90,3.21,3.51,3.75,3.98,4.18,...,8.37
$std_{neg}(n)$,0.36,0.74,1.11,1.45,1.76,2.02,2.28,2.50,2.71,2.88,...,7.13
$quant_{0.995}(n)$,3.49,6.17,8.60,10.86,12.90,14.74,16.60,18.10,19.68,21.14,...,86.68
$quant_{0.005}(n)$,0.00,0.05,0.19,0.42,0.71,1.05,1.42,1.83,2.24,2.70,...,46.48

In [13]:
std_pos = lookup_table_vol.loc["$std_{pos}(n)$"].astype(float).values
std_neg = lookup_table_vol.loc["$std_{neg}(n)$"].astype(float).values
stds = np.concatenate((std_pos, std_neg))
highest_value = np.max(stds)
sem = highest_value / np.sqrt(n_simulations_pt_1 * n_simulations_pt_2)
print("The highest standard error of means is " + "{:.4f}".format(sem))

The highest standard error of means is 0.0084